apiVersion: v1

kind: Service

metadata:
  name: institutional-quant-service

spec:

  type: LoadBalancer

  selector:
    app: institutional-quant

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8501